#!/usr/bin/env bash
set -euo pipefail

ARM=${ARM:?Set ARM to crop336_roi224 or spacing07072_448_roi384}
DATA_ROOT=${DATA_ROOT:?Set DATA_ROOT}
PROCESSED_DATA_ROOT=${PROCESSED_DATA_ROOT:-${DATA_ROOT}/processed}
case "${ARM}" in
  crop336_roi224)
    EXPERIMENT_TAG=WORD112_C336_R224
    PROCESSED_ROOT=${PROCESSED_DATA_ROOT}/OWT_Common8_112_NATIVE/WORD
    MANIFEST_TAG=native112
    EXPECTED_SPACING="1 1 2"
    INPUT_SIZE=336
    GLOBAL_CROP_SIZE=336
    ROI_CROP_SIZE=224
    ;;
  spacing07072_448_roi384)
    EXPERIMENT_TAG=WORD07072_C448_R384
    PROCESSED_ROOT=${PROCESSED_DATA_ROOT}/OWT_Common8_07072_NATIVE/WORD
    MANIFEST_TAG=native07072
    EXPECTED_SPACING="0.7 0.7 2"
    INPUT_SIZE=448
    GLOBAL_CROP_SIZE=448
    ROI_CROP_SIZE=384
    ;;
  *)
    echo "Unknown ARM: ${ARM}" >&2
    exit 2
    ;;
esac

TRAIN_CSV=${PROCESSED_ROOT}/csv/WORD_Training_2D_${MANIFEST_TAG}.csv
VAL_CSV=${PROCESSED_ROOT}/csv/WORD_Test_2D_${MANIFEST_TAG}.csv
PREPROCESS_SUMMARY=${PROCESSED_ROOT}/metadata/preprocess_summary.json
ROI_INDEX=${PROCESSED_ROOT}/metadata/small_organ_roi_index.json
ROI_POSITIVE_SAMPLE_COUNTS="4392 4875 5070 1631 3827 3753 7327 5556"
ROI_FREQUENCY_DATASET_SIZE=28586
export ARM EXPERIMENT_TAG PROCESSED_ROOT MANIFEST_TAG EXPECTED_SPACING
export PROCESSED_DATA_ROOT
export INPUT_SIZE GLOBAL_CROP_SIZE ROI_CROP_SIZE
export TRAIN_CSV VAL_CSV PREPROCESS_SUMMARY ROI_INDEX
export ROI_POSITIVE_SAMPLE_COUNTS ROI_FREQUENCY_DATASET_SIZE
